# Generated by Django 2.0 on 2018-11-15 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.TextField(max_length=10)),
                ('current_college', models.TextField(max_length=30)),
                ('current_address', models.TextField(max_length=100)),
                ('gender', models.TextField(choices=[('M', 'Male'), ('F', 'Female'), ('OT', 'Other')], default='')),
                ('current_year_of_study', models.TextField(choices=[('Year_1', '1st Year'), ('Year_2', '2nd Year'), ('Year_3', '3rd Year'), ('Year_4', '4th Year')], default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
