# Generated by Django 2.0 on 2018-11-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='encarta_id',
            field=models.CharField(default='Not Generated', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_college',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='current_year_of_study',
            field=models.CharField(choices=[('Year_1', '1st Year'), ('Year_2', '2nd Year'), ('Year_3', '3rd Year'), ('Year_4', '4th Year')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('OT', 'Other')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
    ]
