# Generated by Django 2.0 on 2018-11-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_participation_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='verified',
        ),
    ]
