# Generated by Django 2.0 on 2018-11-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20181121_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='prize',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
